name: election_app
description: تطبيق الانتخابات للويندوز والماك

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # حزم المصادقة البديلة
  window_manager: ^0.3.3
  platform: ^3.1.0
  local_auth: ^2.1.7
  image: ^4.0.17
  # باقي التبعيات
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  excel: ^2.0.1
  camera: ^0.10.0+3
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_animate: ^4.1.1+1
  provider: ^6.1.1
  biometric_storage: ^5.0.1
  connectivity_plus: ^6.1.4
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  image_picker_web: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hand_outline.png